// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzxrhjiogsmexsnzidej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6eHJoamlvZ3NtZXhzbnppZGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzk2NTEsImV4cCI6MjA3Mzg1NTY1MX0.ZehJ2BM1xM9ZEU49DSZdgiOwSJgyl2cCV8scdt1pK0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});